
[World]

	[World.Ores]

		[World.Ores.Apatite]
			#Max number of veins per chunk; set to 0 to disable.
			#Range: 0 ~ 256
			"Vein Count" = 4
			#Max size of the vein.
			#Range: 1 ~ 256
			"Vein Size" = 9
			#Minimum Y spawn.
			#Range: -2048 ~ 2048
			"Min Y" = -16
			#Maximum Y spawn.
			#Range: -2048 ~ 2048
			"Max Y" = 96

		[World.Ores.Silver]
			#Max number of veins per chunk; set to 0 to disable.
			#Range: 0 ~ 256
			"Vein Count" = 4
			#Max size of the vein.
			#Range: 1 ~ 256
			"Vein Size" = 8
			#Minimum Y spawn.
			#Range: -2048 ~ 2048
			"Min Y" = -60
			#Maximum Y spawn.
			#Range: -2048 ~ 2048
			"Max Y" = 40

		[World.Ores.Lead]
			#Max number of veins per chunk; set to 0 to disable.
			#Range: 0 ~ 256
			"Vein Count" = 6
			#Max size of the vein.
			#Range: 1 ~ 256
			"Vein Size" = 8
			#Minimum Y spawn.
			#Range: -2048 ~ 2048
			"Min Y" = -60
			#Maximum Y spawn.
			#Range: -2048 ~ 2048
			"Max Y" = 40

		[World.Ores.Nickel]
			#Max number of veins per chunk; set to 0 to disable.
			#Range: 0 ~ 256
			"Vein Count" = 4
			#Max size of the vein.
			#Range: 1 ~ 256
			"Vein Size" = 8
			#Minimum Y spawn.
			#Range: -2048 ~ 2048
			"Min Y" = -40
			#Maximum Y spawn.
			#Range: -2048 ~ 2048
			"Max Y" = 120

		[World.Ores.Sulfur]
			#Max number of veins per chunk; set to 0 to disable.
			#Range: 0 ~ 256
			"Vein Count" = 2
			#Max size of the vein.
			#Range: 1 ~ 256
			"Vein Size" = 7
			#Minimum Y spawn.
			#Range: -2048 ~ 2048
			"Min Y" = -16
			#Maximum Y spawn.
			#Range: -2048 ~ 2048
			"Max Y" = 32

		[World.Ores.Tin]
			#Max number of veins per chunk; set to 0 to disable.
			#Range: 0 ~ 256
			"Vein Count" = 6
			#Max size of the vein.
			#Range: 1 ~ 256
			"Vein Size" = 9
			#Minimum Y spawn.
			#Range: -2048 ~ 2048
			"Min Y" = -20
			#Maximum Y spawn.
			#Range: -2048 ~ 2048
			"Max Y" = 60

		[World.Ores.Niter]
			#Max number of veins per chunk; set to 0 to disable.
			#Range: 0 ~ 256
			"Vein Count" = 2
			#Max size of the vein.
			#Range: 1 ~ 256
			"Vein Size" = 7
			#Minimum Y spawn.
			#Range: -2048 ~ 2048
			"Min Y" = -16
			#Maximum Y spawn.
			#Range: -2048 ~ 2048
			"Max Y" = 64

